name: Build ISO

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: archlinux:latest
      options: --privileged

    steps:
      - uses: actions/checkout@v4

      - name: Get database files
        run: pacman -Sy

      - name: Install ArchISO
        run: pacman -S --noconfirm archiso

      - name: Build the ISO
        run: |
          cd $GITHUB_WORKSPACE
          rm -rf ./out
          mkarchiso . -v

      - name: Upload to Release
        #uses: Shopify/upload-to-release@v2.0.0 # SHOPIFY?!?!
        #with:
        #  name: Latest Kat Linux release
        #  path: $GITHUB_WORKSPACE/out/*
        #  repo-token: ${{ secrets.GITHUB_TOKEN }}
        uses: fnkr/github-action-ghr@v1.3
          
