name: Build ISO

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: archlinux:latest
      options: --privileged

    steps:
      - uses: actions/checkout@v4

      - name: Get database files
        run: pacman -Sy

      - name: Install ArchISO
        run: pacman -S --noconfirm archiso

      - name: Build the ISO
        run: |
          cd $GITHUB_WORKSPACE
          rm -rf ./out
          mkarchiso . -v
          mv ./out/* /

      - name: GitHub Release
        uses: softprops/action-gh-release@v2.5.0
        with:
          tag_name: latest
          name: Latest ArchISO Build
          body: |
            Automated ArchISO build from commit ${{ github.sha }}
            Built on: ${{ github.event.head_commit.timestamp }}
          files: /*.iso
          
